<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.dbeaver.common</groupId>
        <artifactId>com.dbeaver.common.main</artifactId>
        <version>2.6.0-SNAPSHOT</version>
        <relativePath>../dbeaver-common/pom.xml</relativePath>
    </parent>

    <groupId>org.jkiss.dbeaver</groupId>
    <artifactId>dbeaver</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <dbeaver-product>DBeaver</dbeaver-product>

        <!-- Eclipse Platform version, to match with the 'eclipse-version' common property -->
        <eclipse-platform-version>4.38.0</eclipse-platform-version>
        <!-- Eclipse SWT version, to match with the 'eclipse-version' common property -->
        <swt-version>3.132.0</swt-version>
        <!-- temp FreeBSD p2 repo, until Eclipse's official p2 repo supports FreeBSD aarch64/x86_64 platforms -->
        <freebsd-p2-repo.url>https://chirontt.github.io/p2/platform/repository/${eclipse-platform-version}/</freebsd-p2-repo.url>

        <!-- embedded JustJ JRE settings, using the 'java.version' common property -->
        <justj-jre-version>${java.version}</justj-jre-version>
        <justj.jres.repository>https://download.eclipse.org/justj/jres/${justj-jre-version}/updates/release/latest</justj.jres.repository>
        <!-- the JustJ execution environment for the target-platform-configuration -->
        <execution.environment>org.eclipse.justj.openjdk.hotspot.jre.full.stripped-${justj-jre-version}</execution.environment>

        <key.storage.path>/etc/</key.storage.path>
        <tsa/>
    </properties>

    <modules>
        <!-- dbeaver-jdbc-libsql-->
        <module>../dbeaver-jdbc-libsql</module>

        <module>plugins</module>
        <module>features</module>
        <module>product</module>
    </modules>

    <repositories>
        <repository>
            <!-- Eclipse JustJ p2 repo -->
            <id>justj-p2-repo</id>
            <url>${justj.jres.repository}</url>
            <layout>p2</layout>
        </repository>
        <!-- temp FreeBSD p2 repo, until Eclipse's official p2 repo supports FreeBSD aarch64/x86_64 platforms -->
        <repository>
            <id>freebsd-p2-repo</id>
            <url>${freebsd-p2-repo.url}</url>
            <layout>p2</layout>
        </repository>
    </repositories>

    <build>
        <sourceDirectory>${project.basedir}/src</sourceDirectory>
        <testSourceDirectory>${project.basedir}/tests</testSourceDirectory>
        <plugins>
            <!-- Tycho build -->
            <plugin>
                <groupId>org.eclipse.tycho</groupId>
                <artifactId>target-platform-configuration</artifactId>
                <version>${tycho-version}</version>
                <configuration>
                    <executionEnvironment>${execution.environment}</executionEnvironment>
                    <pomDependencies>consider</pomDependencies>
                    <environments>
                        <environment>
                            <os>win32</os>
                            <ws>win32</ws>
                            <arch>x86_64</arch>
                        </environment>
                        <environment>
                            <os>win32</os>
                            <ws>win32</ws>
                            <arch>aarch64</arch>
                        </environment>
                        <environment>
                            <os>linux</os>
                            <ws>gtk</ws>
                            <arch>x86_64</arch>
                        </environment>
                        <environment>
                            <os>linux</os>
                            <ws>gtk</ws>
                            <arch>aarch64</arch>
                        </environment>
                        <environment>
                            <os>linux</os>
                            <ws>gtk</ws>
                            <arch>riscv64</arch>
                        </environment>
                        <environment>
                            <os>macosx</os>
                            <ws>cocoa</ws>
                            <arch>x86_64</arch>
                        </environment>
                        <environment>
                            <os>macosx</os>
                            <ws>cocoa</ws>
                            <arch>aarch64</arch>
                        </environment>
                    </environments>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.eclipse.tycho</groupId>
                <artifactId>tycho-maven-plugin</artifactId>
                <version>${tycho-version}</version>
                <extensions>true</extensions>
            </plugin>

            <plugin>
                <groupId>org.eclipse.tycho</groupId>
                <artifactId>tycho-compiler-plugin</artifactId>
                <version>${tycho-version}</version>
                <configuration>
                    <useProjectSettings>false</useProjectSettings>
                    <release>${java.version}</release>
                    <compilerVersion>${java.version}</compilerVersion>
                </configuration>
            </plugin>

            <!-- Set Built-By info -->
            <plugin>
                <groupId>org.eclipse.tycho</groupId>
                <artifactId>tycho-packaging-plugin</artifactId>
                <version>${tycho-version}</version>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <Built-By>dbeaver.io</Built-By>
                            <Created-By>dbeaver.io</Created-By>
                            <Build-Time>${maven.build.timestamp}</Build-Time>
                        </manifestEntries>
                        <addMavenDescriptor>false</addMavenDescriptor>
                    </archive>
                </configuration>
            </plugin>

        </plugins>

    </build>

    <profiles>
        <!-- desktop build: includes UI components and products -->
        <profile>
            <id>desktop</id>
            <activation><property><name>!headless-platform</name></property></activation>
            <modules>
                <!-- Tests -->
                <module>test</module>
            </modules>
        </profile>

    </profiles>

</project>
